##############################
# Variables you need to change
##############################

sample: "HMRG_6371"  #Name of the sample to act as base name
reads: "/n/holylfs04/LABS/edwards_lab/Lab/klopez/Hemitriccus/r84147_20230919_181046/1_A01/hifi_reads/m84147_230919_181839_s1.hifi_reads.default.bam /n/holylfs04/LABS/edwards_lab/Lab/klopez/Hemitriccus/r64408e_20230329_173557/1_A01/m64408e_230329_204836.hifi_reads.bam /n/holylfs04/LABS/edwards_lab/Lab/klopez/Hemitriccus/r64408e_20230329_173557/2_B01/m64408e_230331_055941.hifi_reads.bam"  #List of BAM files output from sequencer (include full path). If multiple files, separate by SPACES

#Hifiasm options
use_hiC: "false"  #Indicate whether using HiC data to aid in with assembly (note, NOT the same as HiC scaffolding!)
hiC_read1: " "  #If using HiC, include path to first set of reads in pair
hiC_read2: " "  ##If using HiC, include path to second set of reads in pair

primary_only: "false" #If want only primary assembly (no haplotypes), set to true

#Variables you DON'T need to change:
#Output naming:
hifi_outdir: "results/hifiasm_output_RAW"
assem_outdir: "results/assembly"
